// Terms.jsx

import '../styles/Legal.css';

export default function Terms() {
  return (
    <div className="legal-page">
      <div className="legal-card">
        <h1>Terms of Use</h1>

        <p className="legal-updated">
          Last updated: 1 May 2026
        </p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By creating an account or using GlucoBuddy, you agree
            to these Terms of Use.
          </p>
        </section>

        <section>
          <h2>2. Intended Use</h2>
          <p>
            GlucoBuddy is designed for personal diabetes tracking,
            data logging, and educational insight purposes only.
          </p>
        </section>

        <section>
          <h2>3. Not Medical Advice</h2>
          <p>
            GlucoBuddy does not replace professional medical advice,
            diagnosis, or treatment.
          </p>

          <p>
            Users must consult healthcare professionals before
            making treatment or insulin dosage decisions.
          </p>
        </section>

        <section>
          <h2>4. User Responsibilities</h2>
          <p>Users are responsible for:</p>

          <ul>
            <li>Maintaining account security</li>
            <li>Providing accurate information</li>
            <li>Reviewing logged health data carefully</li>
            <li>Using the application responsibly</li>
          </ul>
        </section>

        <section>
          <h2>5. Data Accuracy</h2>
          <p>
            GlucoBuddy does not guarantee the accuracy,
            completeness, or reliability of calculations,
            analytics, or predictions generated by the platform.
          </p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>
            GlucoBuddy and its developers are not liable for any
            damages, health outcomes, or losses resulting from use
            of the platform.
          </p>
        </section>

        <section>
          <h2>7. Account Termination</h2>
          <p>
            Accounts may be suspended or removed if users misuse
            the platform or violate these terms.
          </p>
        </section>

        <section>
          <h2>8. Changes to These Terms</h2>
          <p>
            These Terms of Use may be updated periodically.
            Continued use of the platform indicates acceptance
            of any changes.
          </p>
        </section>
      </div>
    </div>
  );
}